---
- name: Dump facts
  hosts: serverb
  become: false
  tasks:
    - name: Print Facts
      debug: 
        var: ansible_facts
    - name: Output to File
      copy:
        content: "The FQDN is {{ ansible_facts.fqdn }}\n"
        dest: '/tmp/{{ inventory_hostname }}.FQDN.txt'
      delegate_to: workstation
